# -*- coding: utf-8 -*-
"""Project Phase EL_DA1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1etW2a8A0Tji5VEEm2hKcyd4M_RmgDPGh
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd
orders = pd.read_csv("orders.csv")
returns = pd.read_csv("returns.csv")
df = orders.merge(returns, on="order_id", how="left")
df['return_flag'] = df['return_flag'].fillna(0)
df = df.drop_duplicates()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
cols = ['category','supplier','channel','state']
le = LabelEncoder()
for col in cols:
    df[col] = le.fit_transform(df[col])
X = df[['price','quantity','category','supplier','channel','state']]
y = df['return_flag']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
model = LogisticRegression()
model.fit(X_train, y_train)
df['return_probability'] = model.predict_proba(X)[:,1]

high_risk = df[df['return_probability'] > 0.7]
high_risk[['product_id','category','supplier','return_probability']] \
    .to_csv("high_risk_products.csv", index=False)