# -*- coding: utf-8 -*-
"""Task 7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nJalHk4dlE9vvulciG8tggfbpCBIs42O
"""

import os
import sqlite3
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

from google.colab import files

uploaded = files.upload()

df = pd.read_excel("sales_data.xlsx")   # Excel file you created
conn = sqlite3.connect("sales_data.db")
df.to_sql("sales", conn, if_exists="replace", index=False)
query_qty = """
SELECT SUM(Quantity) AS total_quantity_sold
FROM sales;
"""
total_qty = pd.read_sql(query_qty, conn)
print("Total Quantity Sold:")
print(total_qty)
query_revenue = """
SELECT SUM(Revenue) AS total_revenue
FROM sales;
"""
total_revenue = pd.read_sql(query_revenue, conn)
print("\nTotal Revenue:")
print(total_revenue)
query_category = """
SELECT Category, SUM(Revenue) AS revenue
FROM sales
GROUP BY Category;
"""
category_revenue = pd.read_sql(query_category, conn)
print("\nCategory-wise Revenue:")
print(category_revenue)
plt.bar(category_revenue["Category"], category_revenue["revenue"])
plt.xlabel("Category")
plt.ylabel("Revenue")
plt.title("Revenue by Category")
plt.xticks(rotation=45)
plt.show()
conn.close()