# -*- coding: utf-8 -*-
"""Task 6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ei9POnMojYgCV3ycJIW_FKoF88Q3CdLJ
"""

from google.colab import files
files.upload()

import pandas as pd

df = pd.read_excel("online_sales.xlsx")
df.head()

import sqlite3
conn = sqlite3.connect("online_sales.db")
df.to_sql("orders", conn, if_exists="replace", index=False)
conn.close()

import sqlite3
import pandas as pd
conn = sqlite3.connect("online_sales.db")
query = """
SELECT
    CAST(strftime('%Y', order_date) AS INTEGER) AS year,
    CAST(strftime('%m', order_date) AS INTEGER) AS month,
    SUM(amount) AS total_revenue,
    COUNT(DISTINCT order_id) AS order_volume
FROM orders
GROUP BY year, month
ORDER BY year, month;
"""
result = pd.read_sql(query, conn)
print(result)

conn.close()