# -*- coding: utf-8 -*-
"""Task 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UQUDNfCtjyEnEe0mu7T5rHPUoX3nbYEP
"""

from google.colab import files
uploaded = files.upload()
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv("ecommerce_dataset_updated.csv")
df.info()
df.describe()
df.columns

if 'Category' in df.columns:
    df['Category'].value_counts()
if 'Payment_Method' in df.columns:
    df['Payment_Method'].value_counts()
sns.pairplot(df.select_dtypes(include=['int64', 'float64']))
plt.show()
corr = df.select_dtypes(include=['int64', 'float64']).corr()
sns.heatmap(corr, annot=True)
plt.show()
df.select_dtypes(include=['int64', 'float64']).hist()
plt.show()
sns.scatterplot(x='Category', y='Final_Price(Rs.)', data=df)
plt.show()
category_summary = (
    df.groupby('Category')['Final_Price(Rs.)']
    .sum()
    .reset_index()
)
sns.barplot(x='Category', y='Final_Price(Rs.)', data=category_summary)
plt.xticks(rotation=45)
plt.show()